### ISSUE TITLE
Go install fails

### ISSUE THREAD

**Issue by DBL-Lee** [danielvladco/go-proto-gql#25]
I'm using Go 1.16.2 go install requires me to run go get and go get fails.

```
> go install github.com/danielvladco/go-proto-gql/protoc-gen-gql
no required module provides package github.com/danielvladco/go-proto-gql/protoc-gen-gql; to add it:
	go get github.com/danielvladco/go-proto-gql/protoc-gen-gql


> go get github.com/danielvladco/go-proto-gql/protoc-gen-gql
# github.com/danielvladco/go-proto-gql/pkg/generator
go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.0/pkg/generator/generator.go:634:68: cannot use gql.E_Field (type *"github.com/gogo/protobuf/proto".ExtensionDesc) as type protoreflect.ExtensionType in argument to "google.golang.org/protobuf/proto".GetExtension:
	*"github.com/gogo/protobuf/proto".ExtensionDesc does not implement protoreflect.ExtensionType (missing InterfaceOf method)
go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.0/pkg/generator/utils.go:16:67: cannot use gql.E_RpcType (type *"github.com/gogo/protobuf/proto".ExtensionDesc) as type protoreflect.ExtensionType in argument to "google.golang.org/protobuf/proto".GetExtension:
	*"github.com/gogo/protobuf/proto".ExtensionDesc does not implement protoreflect.ExtensionType (missing InterfaceOf method)
go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.0/pkg/generator/utils.go:27:68: cannot use gql.E_SvcType (type *"github.com/gogo/protobuf/proto".ExtensionDesc) as type protoreflect.ExtensionType in argument to "google.golang.org/protobuf/proto".GetExtension:
	*"github.com/gogo/protobuf/proto".ExtensionDesc does not implement protoreflect.ExtensionType (missing InterfaceOf method)
```

Any idea on how to solve this?

**Comment by danielvladco** [comment]
Can you show your go.mod?

**Comment by DBL-Lee** [comment]
Sure!

```
go 1.16

require (
	github.com/fullstorydev/grpcui v1.1.0 // indirect
	google.golang.org/grpc v1.36.1 // indirect
	google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.1.0 // indirect
	google.golang.org/protobuf v1.26.0 // indirect
)
```

**Comment by danielvladco** [comment]
I was able to reproduce the issue with go 1.16. I will fix it the following days.

Please use this command outside go module directory for now
```
 go install github.com/danielvladco/go-proto-gql/protoc-gen-gql@v0.8.0
```

**Comment by DBL-Lee** [comment]
Running that still returns the same error. I will wait for your fix!

**Comment by danielvladco** [comment]
I pushed a new version today, check if it works with `v0.8.1`

**Comment by danielvladco** [comment]
If it still fails try:
```
go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql
go install github.com/danielvladco/go-proto-gql/protoc-gen-gogql
```

**Comment by danielvladco** [comment]
@DBL-Lee Please try the steps above and check if your issue is solved, if yes please close the issue

**Comment by DBL-Lee** [comment]
Thank you for your updatee!

now go get fails with the following error:

```
go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql

github.com/danielvladco/go-proto-gql/protoc-gen-gogql imports
	github.com/danielvladco/go-proto-gql/pkg/generator imports
	github.com/danielvladco/go-proto-gql/pb: ambiguous import: found package github.com/danielvladco/go-proto-gql/pb in multiple modules:
	github.com/danielvladco/go-proto-gql v0.8.2 (/Users/zichuan/go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.2/pb)
	github.com/danielvladco/go-proto-gql/pb v0.6.0 (/Users/zichuan/go/pkg/mod/github.com/danielvladco/go-proto-gql/pb@v0.6.0)
```

**Comment by danielvladco** [comment]
for some reason your go compiler tries to find `github.com/danielvladco/go-proto-gql/pb v0.6.0` which is a older package and no longer used in version 8.

Try cleaning all your cache:
```
go clean
go clean -modcache
```

**Comment by DBL-Lee** [comment]
Still facing the similar error after cleaning the mod cache🤔 

```
go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql

go: downloading github.com/danielvladco/go-proto-gql v0.8.2
go: downloading google.golang.org/protobuf v1.26.0
go: downloading github.com/vektah/gqlparser v1.1.2
go: downloading github.com/jhump/protoreflect v1.8.2
go: downloading github.com/danielvladco/go-proto-gql/pb v0.6.0
go: downloading github.com/vektah/gqlparser/v2 v2.1.0
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/danielvladco/go-proto-gql/pb v0.6.1
github.com/danielvladco/go-proto-gql/protoc-gen-gogql imports
	github.com/danielvladco/go-proto-gql/pkg/generator imports
	github.com/danielvladco/go-proto-gql/pb: ambiguous import: found package github.com/danielvladco/go-proto-gql/pb in multiple modules:
	github.com/danielvladco/go-proto-gql v0.8.2 (/Users/zichuan/go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.2/pb)
	github.com/danielvladco/go-proto-gql/pb v0.6.0 (/Users/zichuan/go/pkg/mod/github.com/danielvladco/go-proto-gql/pb@v0.6.0)
```

**Comment by danielvladco** [comment]
@DBL-Lee, this is weird, I cannot reproduce this issue... looks like it's a go mod problem

Check this issue, maybe it will help.
https://github.com/golang/go/issues/44129

Also you can try using go 1.14 or 1.15 to see if the issue goes away

**Comment by DBL-Lee** [comment]
@danielvladco I downgraded to 1.15 and still same problem. I tried on my friends laptop and he has the same problem too

**Comment by danielvladco** [comment]
I am 90% sure this is because of a weird cache problem.
It tries to download an old package `github.com/danielvladco/go-proto-gql/pb@v0.6.0` that is no longer used.

if you install it on a fresh system if will not show you this error. 

For example you could try to install it in docker and you will not see this error
```
$ docker run -it golang sh
$ mkdir test
$ cd test
$ go mod init test
$ go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql@v0.8.2
$ go install github.com/danielvladco/go-proto-gql/protoc-gen-gogql
```

2 more things you can try
- Delete `~/go/pkg/mod`
- Delete and regenerate `go.sum`

**Comment by DBL-Lee** [comment]
There appears to be a go.mod in my root directory which is causing this problem. Deleting it would make
`go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql` succeed in a directory without go.mod.

But `go install` fails with
```
go install github.com/danielvladco/go-proto-gql/protoc-gen-gogql@master: github.com/danielvladco/go-proto-gql@v0.8.2
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

I will try your suggestions! Thanks

**Comment by DBL-Lee** [comment]
I couldn't figure out how to solve this. I even deleted the entire `~/go/pkg` and the error still persists. Since it works in docker, I guess I will build my protos in docker.

**Comment by danielvladco** [comment]
> There appears to be a go.mod in my root directory which is causing this problem. Deleting it would make
> `go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql` succeed in a directory without go.mod.
> 
> But `go install` fails with
> 
> ```
> go install github.com/danielvladco/go-proto-gql/protoc-gen-gogql@master: github.com/danielvladco/go-proto-gql@v0.8.2
> 	The go.mod file for the module providing named packages contains one or
> 	more replace directives. It must not contain directives that would cause
> 	it to be interpreted differently than if it were the main module.
> ```
> 
> I will try your suggestions! Thanks

This error is expected since I am using replacements but if you run `go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql@v0.8.2` it will go away

Regenerating your `go.sum` might help, and make sure you don't have `github.com/danielvladco/go-proto-gql/pb` in your `go.mod`

**Comment by DBL-Lee** [comment]
when I delete go.mod and go.sum and run `go mod init` on my existing directory, the following is what is in my go.mod.
```
go 1.16

require (
	google.golang.org/grpc v1.33.2
	google.golang.org/protobuf v1.26.0
)
```

Then when I get the error:
```
 go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql@v0.8.2
github.com/danielvladco/go-proto-gql/protoc-gen-gogql imports
	github.com/danielvladco/go-proto-gql/pkg/generator imports
	github.com/danielvladco/go-proto-gql/pb: ambiguous import: found package github.com/danielvladco/go-proto-gql/pb in multiple modules:
	github.com/danielvladco/go-proto-gql v0.8.2 (/Users/zichuan/go/pkg/mod/github.com/danielvladco/go-proto-gql@v0.8.2/pb)
	github.com/danielvladco/go-proto-gql/pb v0.6.0 (/Users/zichuan/go/pkg/mod/github.com/danielvladco/go-proto-gql/pb@v0.6.0)
```

However, after I manually delete the requires, the `go get -t github.com/danielvladco/go-proto-gql/protoc-gen-gogql@v0.8.2` succeeds! Even after adding back the two lines, it still works 🎉
